name: "DevSecOps Pipeline"

# Cumple con la rúbrica: Activa en PR a main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-security:
    name: "Validación y Seguridad"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format & Validate
        run: |
          terraform fmt -check
          terraform validate

      - name: Run TFLint
        run: |
          tflint --init
          tflint

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          soft_fail: true # Evita bloquear por reglas excesivas, solo muestra warnings

      - name: Generar Plan de Terraform para OPA
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: "us-east-1"
          TF_VAR_public_key: ${{ secrets.TF_VAR_PUBLIC_KEY }}
        run: |
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: OPA Policy - No SSH Público
        run: |
          opa eval -i tfplan.json -d terraform_ssh_check.rego "data.terraform.ssh.violation" | grep -q '"result": \[\]' || (echo "VIOLACION: SSH abierto al publico detectado." && exit 1)

      - name: OPA Policy - Solo T2 Micro
        run: |
          opa eval -i tfplan.json -d terraform_ec2_check.rego "data.terraform.ec2.violation" | grep -q '"result": \[\]' || (echo "VIOLACION: Tipo de instancia no permitido." && exit 1)

  terraform-apply:
    name: "Despliegue (Terraform Apply)"
    runs-on: ubuntu-latest
    needs: validate-and-security
    if: github.ref == 'refs/heads/main' # Solo despliega cuando se hace push/merge a main
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init & Apply
        env:
          TF_VAR_public_key: ${{ secrets.TF_VAR_PUBLIC_KEY }}
        run: |
          terraform init
          terraform apply -auto-approve